# Generated by Django 5.2.2 on 2025-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_alter_dish_options_dish_avg_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
    ]
