# Generated by Django 5.2.2 on 2026-01-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_category_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Вкажіть вагу в грамах', verbose_name='Вага порції (г)'),
        ),
    ]
