# Generated by Django 5.2.2 on 2026-01-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_dish_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Вага порції '),
        ),
    ]
