# Generated by Django 5.2.2 on 2026-01-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_dish_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='weight',
        ),
        migrations.AddField(
            model_name='dish',
            name='portion_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Вага / обʼєм порції'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='unit',
            field=models.CharField(choices=[('g', 'г'), ('ml', 'мл')], default='g', max_length=2, verbose_name='Одиниця виміру'),
        ),
    ]
